rename custom_pi

diff --git a/src/nightly_build_scripts/custompios_nightly_build b/src/nightly_build_scripts/custompios_nightly_build
--- a/src/nightly_build_scripts/custompios_nightly_build
+++ b/src/nightly_build_scripts/custompios_nightly_build
@@ -3,9 +3,9 @@ set -x
 set -e
 
 export DIST_PATH=/distro
-export CUSTOM_PI_OS_PATH=/anbnkiOS
+export ANBN_KI_OS_PATH=/anbnkiOS
 
-source "$CUSTOM_PI_OS_PATH/argparse.bash" || exit 1
+source "$ANBN_KI_OS_PATH/argparse.bash" || exit 1
 argparse "$@" <<EOF || exit 1
 
 parser.add_argument('WORKSPACE_SUFFIX', nargs='?', default="default", help="The workspace folder suffix used folder")
@@ -40,7 +40,7 @@ pushd "${DIST_PATH}"
     #export OCTOPI_OCTOPRINT_REPO_BUILD='http://localhost/git/OctoPrint.git/'
     #export OCTOPI_MJPGSTREAMER_REPO_BUILD='http://localhost/git/mjpg-streamer.git/'
     #export OCTOPI_WIRINGPI_REPO_BUILD='http://localhost/git/wiringPi.git/'
-    ${CUSTOM_PI_OS_PATH}/build_custom_os "${WORKSPACE_SUFFIX}"
+    ${ANBN_KI_OS_PATH}/build_custom_os "${WORKSPACE_SUFFIX}"
     exit_code=$?
     if [ $exit_code -ne 0 ]; then
         echo "build script failed"
@@ -52,15 +52,15 @@ pushd "${DIST_PATH}"
         EXTRA_FLAGS="--sha256"
     fi
     
-    bash -x ${CUSTOM_PI_OS_PATH}/release ${EXTRA_FLAGS} "${WORKSPACE_SUFFIX}"
+    bash -x ${ANBN_KI_OS_PATH}/release ${EXTRA_FLAGS} "${WORKSPACE_SUFFIX}"
     
     if [ "${RPI_IMAGER}" == "yes" ]; then
-        if [ -z "${CUSTOM_PI_OS_PATH}" ];then
-            echo "Error: you must have \${CUSTOM_PI_OS_PATH} to generate a rpi-imager snipplet"
+        if [ -z "${ANBN_KI_OS_PATH}" ];then
+            echo "Error: you must have \${ANBN_KI_OS_PATH} to generate a rpi-imager snipplet"
             exit 1
         fi
-        source "${CUSTOM_PI_OS_PATH}/config" "${WORKSPACE_SUFFIX}"
-        "${CUSTOM_PI_OS_PATH}/make_rpi-imager-snipplet.py" --rpi_imager_url "${RPI_IMAGER_URL}" -- "${WORKSPACE_SUFFIX}"
+        source "${ANBN_KI_OS_PATH}/config" "${WORKSPACE_SUFFIX}"
+        "${ANBN_KI_OS_PATH}/make_rpi-imager-snipplet.py" --rpi_imager_url "${RPI_IMAGER_URL}" -- "${WORKSPACE_SUFFIX}"
     fi
     
     chmod 777 ${DIST_PATH}/workspace${WORKSPACE_POSTFIX}/*
